In [44]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.linear_model as sk
import sklearn.model_selection as skm
import pandas as pd
from pandas.tools import plotting as pt

data = pd.read_csv('Cars93.csv')
X = np.array(data[['MPG.city', 'MPG.highway', 'EngineSize','Horsepower', 'RPM', 'Rev.per.mile','Fuel.tank.capacity', 
          'Passengers', 'Length',   'Wheelbase', 'Width', 'Turn.circle', 'Weight']], dtype=float)
Y = np.array(data['Price'].values.reshape(-1,1), dtype=float)

Linear = sk.LinearRegression()
Lasso = sk.Lasso(0.0001, normalize = True)
LOO = skm.LeaveOneOut()

In [61]:
alpha_range = np.logspace(-5, 0, num=100, base=10)
C = []
for i in alpha_range:
    lasso = Lasso.fit(X, Y)
    Coefs = [lasso.intercept_, lasso.coef_]
    C.append(Coefs)

C = np.array(C)

[array([-0.00000000e+00, -2.34082561e-01,  1.26780923e+00,  1.47059728e-01,
       -2.37220394e-03,  2.63768594e-03,  1.33918859e-01, -1.44968333e+00,
        1.11767609e-01,  6.35232961e-01, -1.50293992e+00, -5.27680441e-01,
        7.36552689e-04])
 array([-0.00000000e+00, -2.34082561e-01,  1.26780923e+00,  1.47059728e-01,
       -2.37220394e-03,  2.63768594e-03,  1.33918859e-01, -1.44968333e+00,
        1.11767609e-01,  6.35232961e-01, -1.50293992e+00, -5.27680441e-01,
        7.36552689e-04])
 array([-0.00000000e+00, -2.34082561e-01,  1.26780923e+00,  1.47059728e-01,
       -2.37220394e-03,  2.63768594e-03,  1.33918859e-01, -1.44968333e+00,
        1.11767609e-01,  6.35232961e-01, -1.50293992e+00, -5.27680441e-01,
        7.36552689e-04])
 array([-0.00000000e+00, -2.34082561e-01,  1.26780923e+00,  1.47059728e-01,
       -2.37220394e-03,  2.63768594e-03,  1.33918859e-01, -1.44968333e+00,
        1.11767609e-01,  6.35232961e-01, -1.50293992e+00, -5.27680441e-01,
        7.36552689e-0

In [36]:
for train_index, test_index in LOO.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]

In [ ]:
R2 = []
Fits = []
for i in filas(len(X_train[1,:])):
    Fits.append(Lasso.fit())
    