In [25]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import BaggingClassifier


In [114]:
data = pd.read_csv("processed.cleveland.data")

data = data[data != "?"]
data = data.dropna()
y= data["0"].values.reshape(-1,1)
x = data[["63.0","1.0","1.0.1","145.0","233.0","1.0.2","2.0","150.0","0.0","2.3","3.0","0.0.1","6.0"]].values

data = np.array(data)


In [118]:
Y = data[:,13]

X = np.zeros((296,12))


for i in range(0,12):
    for j in range(0,296):
        X[j,i] = data[j,i]
X = X.astype(int)
print(X)

[[67  1  4 ...  1  2  3]
 [67  1  4 ...  2  2  2]
 [37  1  3 ...  3  3  0]
 ...
 [68  1  4 ...  3  2  2]
 [57  1  4 ...  1  2  1]
 [57  0  2 ...  0  2  1]]


In [122]:
regressor = DecisionTreeRegressor()
bagging = BaggingClassifier(regressor, n_estimators = 10)    
bagging.fit(X,y)
#bagging.predict(X)

/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:618: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [ ]:
dimtree = np.linspace(2,300,299)
MSE1 = []
MSE2 = []
MSE3 = []
MSE4 = []
for i in range(2,len(dimtree)):
    regressor = DecisionTreeRegressor()
    bagging = BaggingClassifier(regressor, n_estimators = i)
    bagging.fit(X,y)
    #bagging.predict(X)
    #MSE1.append(mean_squared_error(predict,Y))
    
    regressor = DecisionTreeRegressor()
    bagging = BaggingClassifier(regressor, n_estimators = i,oob_score=True)
    #bagging.fit(X,y)
    #bagging.predict(X)
    #MSE2.append(mean_squared_error(predict,Y))
    
    regressor = RandomForestClassifier()
    bagging = BaggingClassifier(regressor, n_estimators = i)
    #bagging.fit(X,y)
    #bagging.predict(X)
    #MSE3.append(mean_squared_error(predict,Y))
    
    regressor = RandomForestClassifier()
    bagging = BaggingClassifier(regressor, n_estimators = i,oob_score=True)
    #bagging.fit(X,y)
    #bagging.predict(X)
    #MSE4.append(mean_squared_error(predict,Y))
    

    

/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:618: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:618: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:618: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/srv/conda/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:618: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin